name: web-console

on:
  push:
    # temporarily commenting for initial test
    # paths:
      # - packages/web-console/**
    branches-ignore:
      - main
      - refs/tags/*

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '16.13.1'
          cache: 'yarn'

      - name: Install dependencies
        run: yarn install --immutable --immutable-cache --check-cache


      - name: build
        run: yarn workspace @questdb/web-console run build
