name: web-console

on:
  push:

jobs:
  CI:
    name: Build packages/web-console
    runs-on: ubuntu-latest
    services:
      questdb:
        image: questdb/questdb:nightly
        ports: 9000:9000

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '16.13.1'
          cache: 'yarn'

      - name: Install dependencies
        run: yarn install --immutable --immutable-cache

      - name: Build
        run: yarn workspace @questdb/web-console run build

      - name: Run unit tests
        run: yarn workspace @questdb/web-console run test:prod

      - name: run cypress tests
        run: yarn workspace browser-tests test       

      - name: Cypress run
        uses: cypress-io/github-action@v5
        with:
          start: python -m http.server --directory dist 9999

      - name: Publish @questdb/web-console to npm
        if: github.ref == 'refs/heads/main'
        uses: JS-DevTools/npm-publish@v1
        with:
          token: ${{ secrets.NPM_TOKEN }}
          access: public
          check-version: true
          package: ./packages/web-console/package.json
