name: web-console

on:
  push:

jobs:
  build:
    name: Build packages/web-console
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '16.13.1'
          cache: 'yarn'

      - name: Install dependencies
        run: yarn install --immutable --immutable-cache

      - name: build
        run: yarn workspace @questdb/web-console run build

      - name: Publish @questdb/web-console to npm
        # if: github.ref == 'refs/heads/main'
        uses: JS-DevTools/npm-publish@v1
        with:
          token: ${{ secrets.NPM_TOKEN }}
          access: public
          check-version: true
          package: ./packages/web-console/package.json
          dry-run: true
